movie_system/book_movie/urls.py
from django.urls import path
from . import views
app_name = "book_movie"

urlpatterns = [
    path("register/", views.register_user, name="register"),
    path("", views.login_user, name="login"),
    path("accounts/login/", views.login_user, name="login"),
    path("home/login/", views.login_user, name="login"),
    path("movie/login/", views.login_user, name="login"),
    path("home/", views.home, name="home"),
    path("home/logout/", views.logout_user, name="logout"),
    path("movie/logout/", views.logout_user, name="logout"),
    path("my_booking/", views.my_booking, name="my_booking"),
    path("full_ticket/<int:ticket_no>", views.full_ticket, name="full_ticket"),
    
    path("movie/", views.movie_list, name="movie_list"),
    path("movie_details/<int:movie_id>", views.movie_details, name="movie_details"),
    path("movie/add_movie/", views.add_movie, name="add_movie"),
    path("movie_details/update_movie/<int:id>", views.update_movie, name="update_movie"),
    path("movie_details/updated_movie/<int:id>", views.updated_movie, name="updated_movie"),
    path("movie_details/delete_movie/<int:id>", views.delete_movie, name="delete_movie"),
    path("movie_show/<int:movie_id>", views.movie_show, name="movie_show"),
    path("seat_map/<int:Show_id>", views.seat_map, name="seat_map"),
    # path("payment/", views.payment, name="payment"),
    path('payment/', views.payment_page, name='payment'),
    # path('movie/payment_success/', views.payment_success, name='payment_success'),
    path("payment/book_successfully/", views.book_successfully, name="book_successfully"),
    
    path("movie/theater_list/", views.theater_list_admin, name="theater_list_admin"),
    path('movie_details/<int:movie_id>/book/', views.book, name='book'),
    path("movie/<int:movie_id>/theater/", views.theater_list, name="theater_list"),
    path("movie/theater_list/<str:pk>", views.theater_details, name="theater_details"),

    path('movie/theater_list/update_Theater/<int:id>', views.update_Theater, name='update_Theater'),
    path('movie/theater_list_admin/updated_Theater/<int:id>', views.updated_Theater, name='updated_Theater'),
    path('movie/theater_list/delete_theater/<int:id>', views.delete_Theater, name='delete_Theater'),
    path('movie/theater_list/add_theater/', views.add_Theater, name='add_Theater'),
    
    path("movie/show_list/", views.show_list, name="show_list"),
    path("movie/show_list/<int:id>", views.show_details, name="show_details"),
    path("movie/show_list/update_show/<int:id>", views.update_show, name="update_show"),
    path("movie/show_list/updated_show/<int:id>", views.updated_show, name="updated_show"),
    path("movie/show_list/delete_show/<int:id>", views.delete_show, name="delete_show"),
    path("movie/show_list/add_show/", views.add_show, name="add_show"),
    
    path('movie/rating/', views.rating, name='rating'),
    path('movie/rating/add/', views.add_rating, name='add_rating'),
    # path('movie/rating/', views.rating, name="rating"),
    # accounts/login/
]   

movie_system/movie_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book_movie.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_system/templates/add_movie.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AddMovie</title>
    <style>
        body {
            background-color: #f8f9fa; 
        }
    
        .container {
            max-width: 500px;
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #fff; 
        }
    
        input[type="submit"] {
            background-color: #007bff; 
            color: #fff; 
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
    
        input[type="submit"]:hover {
            background-color: #0056b3; 
        }
    </style>
</head>
<body>
{% block content %}
<div class="container py-5">

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ movie_form.as_p }}
        <input type="submit" value="Add Movie">
    </form>
    
</div>
{% endblock %}
</body>
</html>

movie_system/templates/add_rating.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Rating</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'add_rating.css' %}">
   
</head>
<body>
    
{% block content %}
<div class="container py-5">
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ rating.as_p }}
        <input type="submit" value="Add">
        <a href="{% url 'book_movie:rating' %}" class="btn-back">Back to Ratings</a>
    </form>
    
    
</div>
{% endblock %}
</body>
</html>

movie_system/templates/add_theater.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Theater</title>
    <style>
        /* Your existing styles here */
    </style>
</head>
<body>
<div class="container py-5">
    <h2>Add Theater</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ theater_form.as_p }}
        <!-- Set the initial value of the user field to the logged-in user's ID -->
        <input type="hidden" name="user" value="{{ request.user.id }}">
        <input type="submit" value="Add">
    </form>
</div>
</body>
</html>

movie_system/templates/delete_movie.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Movie</title>
</head>
<body>
{% block content %}
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>
{% endblock %}
</body>
</html>

movie_system/templates/delete_theater.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Movie</title>
</head>
<body>
{% block content %}
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this theater ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>
{% endblock %}
</body>
</html>

movie_system/templates/full_ticket.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Full Ticket</title>
    {% bootstrap_css %}
</head>
<body class="p-5">
    <div class="container">
        <h1 class="display-5">Ticket: {{ ticket.ticket_no }}</h1>
        <br>    
        <div class="container">
            
                <p><b>Movie:</b> {{ ticket.Show_id.movie_id.movie_title }}</p>
                <p><b>Theater: </b> {{ ticket.Show_id.Theater_name }}</p>
                <p><b>Show date:</b> {{ ticket.Show_id.Show_date }}</p>
                <p><b>Timing:</b> {{ ticket.Show_id.start_time }} - {{ ticket.Show_id.end_time }}</p>
                <p><b>Screen no:</b> {{ ticket.Show_id.Screen_no }}</p>
                <p><b>Price: </b> {{ ticket.amount }}</p>
            
                <p><b>Seats: </b> 
                    {% for seat in seats %}
                        {{ seat.seat_row }}-{{ seat.seat_col }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

movie_system/templates/home.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-
    target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-
    label="Toggle navigation">    
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="logout/">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#/">Welcome, {{user.username}}</a>
                </li>
                {%if not user.is_staff%}
                <li class="nav-item">
                    <a class="nav-link" href="{%url "book_movie:my_booking"%}">My Booking</a>
                </li>
                {%endif%}
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="login/">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</body>
</html>

movie_system/templates/login.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    {% block content %}    
    <div class="container py-5">
        <h1>Login</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {{ login_form.as_p }}
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="/register/">Create an
    account</a>.</p>
    </div>
    {% endblock %}
</body>
</html>

movie_system/templates/movie_list.html
{% include "home.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie_List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'movie_list.css' %}">
    <style>

        .button-container {
            margin-top: 20px;
        }

        .button-container form {
            display: inline-block;
            margin-right: 10px;
        }

        .button-container form input[type="submit"] {
            background-color: blue; 
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            transition: background-color 0.3s;
        }

        .button-container form input[type="submit"]:hover {
            background-color: #2196f3; 
        }

    </style>
</head>
<body>
    <div>
        {% if user.is_staff %}
            <div class="button-container">
                <form method="POST" action="add_movie/">
                    {% csrf_token %}
                    <input type="submit" value="Add movie">
                </form>
                <form method="POST" action="theater_list/">
                    {% csrf_token %}
                    <input type="submit" value="Theaters">
                </form>
                <form method="POST" action="show_list/">
                    {% csrf_token %}
                    <input type="submit" value="Shows">
                </form>
            </div>
        {% endif %}    
        <div class="button-container">
            <form method="POST" action="rating/">
                {% csrf_token %}
                <input type="submit" value="Rating Of Site">
            </form>
        </div>
        
        <br>
    </div>
    <h1>All Movie List</h1>
    <div class="movies">
        {% for movie in movies %}
            <div class="movie">
                <a href="{% url 'book_movie:movie_details' movie_id=movie.movie_id %}">
                    <img src="{{ movie.img.url }}" alt="{{ movie.movie_title }}">
                </a>
                <h2>{{ movie.movie_title }}</h2>
            </div>
        {% endfor %}
    </div>
</body>
</html>

movie_system/templates/movie_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Show</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'movie_show.css' %}">
</head>
<body>
    {%for theater, movie_show in theater_with_show.items%}
    <div class="theater">
        <h3>{{theater}}</h3>
        <div>
            {%for show in movie_show%}
                <a href="{% url 'book_movie:seat_map' Show_id=show.Show_id %}">
                <span class="show-time"> {{show.start_time}} </span>
                </a>
            {%endfor%}
        </div>
    </div>
    {%endfor%}
</body>
</html>

movie_system/templates/show_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show List</title>
    {% load static %}
</head>
<style>
    body {
        font-family: 'Roboto', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4; 
        color: #333; 
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

    h1 {
        color: #ff5722;
    }

    form {
        margin-bottom: 20px;
    }

    form input[type="text"],
    form input[type="submit"] {
        padding: 12px;
        border-radius: 25px;
        border: 1px solid #ddd; 
        transition: border-color 0.3s;
    }

    form input[type="text"] {
        width: 200px;
    }

    form input[type="submit"] {
        background-color: blue; 
        color: #fff; 
        border: none;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    form input[type="submit"]:hover {
        background-color: #2196f3; 
    }

    .shows {
        margin-top: 20px;
    }

    .show {
        margin-bottom: 20px;
        padding: 15px;
        border-radius: 8px;
        background-color: #f8bbd0; 
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s;
    }

    .show a {
        color: #2196f3; 
        text-decoration: none;
        transition: color 0.3s;
    }

    .show a:hover {
        color: #1565c0; 
    }

    .show:hover {
        transform: translateY(-5px);
    }

    .add-button-container {
        text-align: right;
        margin-bottom: 20px;
    }

    .show-time {
        display: inline-block;
        padding: 5px 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-right: 10px;
    }
    
    .theater {
        border: 1px solid #ccc;
        padding: 10px;
        margin-bottom: 20px;
        border-radius: 5px;
    }
</style>
<body>
    <div class="container">
        {% if user.is_staff%}
            <div class="add-button-container">
                <form method="GET" action="add_show/">
                    {% csrf_token %}
                    <input type="submit" value="Add">
                </form>
            </div>
        {% endif %}
        <BR>
        <center><h1>All show List</h1></center>
        {% comment %} <div class="shows">
            {% for show in shows %}
                <div class="show">
                     <a href="{% url 'book_movie:ShowTime' Theater_name=theater.Theater_name %}">
                        {{ theater.Theater_name }}
                    </a> 
                    <a href="{% url 'book_movie:show_details' id=show.Show_id %}">
                        {{ show.start_time }}
                    </a> 
                    
                </div>
                <br>
            {% endfor %} 
            
        </div> {% endcomment %}
        {%for theater, movie_show in theater_with_show.items%}
            <div class="theater">
                <h3>{{theater}}</h3>
                <div>
                    {%for show in movie_show%}
                        <a href="{% url 'book_movie:show_details' id=show.Show_id %}">
                        <span class="show-time"> {{show.start_time}} </span>
                        </a>
                    {%endfor%}
                </div>
            </div>
        {%endfor%}

    </div>
   
</body>
</html>

movie_system/templates/theater_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Theater Detail</title>
    {% load static %}
</head>
<style>

    body {
        font-family: 'Roboto', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4; 
        color: #333; 
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

    h2 {
        color: #ff7e67;
    }

    p {
        margin: 10px 0;
    }


    form {
        margin-top: 20px;
    }

    form input[type="submit"] {
        padding: 12px 20px;
        border-radius: 25px;
        border: none;
        background-color: blue; 
        color: #fff; 
        cursor: pointer;
        transition: background-color 0.3s;
    }

    form input[type="submit"]:hover {
        background-color: #2196f3; 
    }

</style>
<body>
    
    <div class="container">
        {% if user.is_staff%}
            <form id="updateForm" method="POST" action="">
                {% csrf_token %}
                <input type="hidden" id="id" name="id" value="{{theater.user_id}}">
                <input type="submit" value="Edit">
            </form>
            <form id="deleteForm" method="POST" action="">
                {% csrf_token %}
                <input type="hidden" id="delete_id" name="id" value="{{theater.user_id}}">
                <input type="submit" value="Delete">
            </form>
        {% endif %}
        <form method="POST" action="theater/">
        {% csrf_token %}
        <h2>Theater Name : {{theater.Theater_name}}</h2>
        <p><b>City : </b> {{theater.city}}</p>
        <p><b>Address : </b>{{theater.address}}</p>
        <p><b>Total Screens : </b> {{theater.total_screens}}</p>
        <p><b>User : </b>{{theater.user}}</p>
        </form>
    </div>

    <script>
        document.getElementById('updateForm').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent the form from submitting
            var idValue = document.getElementById('id').value; // Get the value of the id field
            this.action = "update_Theater/" + idValue; // Set the action URL dynamically
            this.submit(); // Submit the form
        });

        document.getElementById('deleteForm').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent the form from submitting
            var deleteIdValue = document.getElementById('delete_id').value; // Get the value of the id field
            this.action = "delete_theater/" + deleteIdValue; // Set the action URL dynamically
            this.submit(); // Submit the form
        });
    </script>

</body>
</html>

movie_system/templates/theater_list.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Theater List</title>
    {% load static %}
</head>
<style>
    body {
        font-family: 'Roboto', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4; 
        color: #333; 
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

    h1 {
        color: #ff5722;
    }

    form {
        margin-bottom: 20px;
    }

    form input[type="text"],
    form input[type="submit"] {
        padding: 12px;
        border-radius: 25px;
        border: 1px solid #ddd; 
        transition: border-color 0.3s;
    }

    form input[type="text"] {
        width: 200px;
    }

    form input[type="submit"] {
        background-color: blue; 
        color: #fff; 
        border: none;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    form input[type="submit"]:hover {
        background-color: #2196f3; 
    }

    .theaters {
        margin-top: 20px;
    }

    .theater {
        margin-bottom: 20px;
        padding: 15px;
        border-radius: 8px;
        background-color: #f8bbd0; 
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s;
    }

    .theater a {
        color: #2196f3; 
        text-decoration: none;
        transition: color 0.3s;
    }

    .theater a:hover {
        color: #1565c0; 
    }

    .theater:hover {
        transform: translateY(-5px);
    }

    .add-button-container {
        text-align: right;
        margin-bottom: 20px;
    }
</style>
<body>
    <div class="container">
        {% if user.is_staff%}
            <div class="add-button-container">
                <form method="POST" action="add_theater/">
                    {% csrf_token %}
                    <input type="submit" value="Add">
                </form>
            </div>
        {% endif %}
        <center><h1>All Theater List</h1></center>
        <div class="theaters">
            {% for theater in theaters %}
                <div class="theater">
                     
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
</body>
</html> -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Theater List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'theater_list.css' %}">
</head>
<body>
    

        <form method="get" action="{% url 'book_movie:theater_list' movie_id=movie_id  %}">
        <label for="selected_date">Select Date:</label>
        <input type="date" id="selected_date" name="selected_date">
        <button type="submit">Submit</button>
        </form>
    
    
    
    {% if theaters %}
    <h1>Theater List</h1>
    <ul>
        {% for show in shows %}
            <li>
                <h2>{{ show.Theater_name.Theater_name }}</h2>
                <a href="{% url 'book_movie:seat_map' Show_id=show.Show_id %}">
                    {{ show.start_time }} - {{ show.end_time }}
                </a>
               
                <p>Release Date: {{ show.Show_date }}</p>
                <p>Screen No: {{ show.Screen_no }}</p>
            </li>
        {% endfor %} 
    </ul>
    {% else %}
    <p>No theaters available for the selected date.</p>
    {% endif %}
</body>
</html>

movie_system/templates/update_show.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Show</title>
</head>
<style>
    body {
        background-color: #f8f9fa; 
    }

    .container {
        max-width: 500px;
        margin: auto;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        background-color: #fff; 
    }

    input[type="submit"] {
        background-color: #007bff; 
        color: #fff; 
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    input[type="submit"]:hover {
        background-color: #0056b3; 
    }
</style>
<body>

    {% block content %}
    <div class="container">
        <form id="updateForm" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ show_form.as_p }}
            <input type="hidden" id="id" name="id" value="{{ show_form.instance.Show_id }}">
            <input type="submit" value="Update">
            
        </form>
        
    </div>
    {% endblock %}
    
</body>
<script>
    document.getElementById('updateForm').addEventListener('submit', function(event) {
        event.preventDefault(); 
        var idValue = document.getElementById('id').value; 
        this.action = "/movie/show_list/updated_show/" + idValue; 
        this.submit(); 
    });
</script>
</html>